[theme]
base = "light"
primaryColor = "#4f46e5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9fafb"
textColor = "#111827"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
